### ISSUE TITLE
Products that are set to be visible to your Company are not showing up in the In App Store before you are logged into your Store account

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/common-header#274]
<b>How it works now:</b>
1. Log into the In App Store with Common Header Testing URL, and open the In App Store. Notice that there is no cart icon, and this is because you are not signed into the store, and you cannot see all the items that are set to be visible to your Company. 
2. Log into the RVA at rva.risevision.com, and open the In App Store. Notice that there is no cart icon, and this is because you are not signed into the store, but you can see all the items that are set to be visible to your Company. 

For further clarification: https://dl.dropboxusercontent.com/u/8237394/Screencasts/2014-10-17_1421.swf

<b>How it should work:</b>
Similar to how the store works in production, even though you are not logged into the store, you shoudl see the items that are set to be visible by your Company.

**Comment by ByronDarlison** [comment]
@robb-price @brianloosbrock @olegrise is this still an open issue or is it closed now? And if still open does this belong to CH and @ezequielc or @alex-deaconu should address or is this an open store defect?

**Comment by hcs0** [comment]
@robb-price @ByronDarlison @olegrise I can't recreate the issue. Also because how CH works in RVA/new app is different now compared to when this issue was brought up. The test CH url also does not work.

**Comment by ByronDarlison** [comment]
Okay @hcs0 Let's close

**Comment by olegrise** [comment]
Agreed.

**Comment by ByronDarlison** [comment]
All, thanks!
