### ISSUE TITLE
Incorrect menu item is being highlighted when pages are opened in a new tab.

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/common-header#360]
We don't properly communicate the page the User is on when selecting a menu item from the common header that opens a new tab. 

Overview here, http://www.screencast.com/t/lxK71vbUsZnS

**Comment by ByronDarlison** [comment]
@alanclayton @olegrise @alex-deaconu @ezequielc I believe this issue is now closed. Can you confirm?

**Comment by alanclayton** [comment]
@ByronDarlison Agreed.
