### ISSUE TITLE
Opening a link from email results in the Spinner forever

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/common-header#378]
<b>How it works now:</b>
When you are not logged into the Store, open Gmail and click on the link to a Store item like an invoice, order or Subscription from an email. Notice that you get the Spinner forever, with this error message in the console:
![2014-12-02_1121](https://cloud.githubusercontent.com/assets/6862256/5266126/bcea419c-7a15-11e4-9963-c98bca641995.png)

<b>How it should work:</b>
You should be prompted to log into the Store to see the item.

**Comment by robb-price** [comment]
Reopened this, and attached the error I am getting in the console now: 
![2015-01-13_0916](https://cloud.githubusercontent.com/assets/6862256/5721906/202dd29a-9b05-11e4-9f69-a8dcdf57a7fb.png)

**Comment by alex-deaconu** [comment]
@robb-price the store-server is returning a 403 error. The Store is expecting a 401 error, as per the fixes to store-server above.

Either way, this is not a Common Header issue. 

To fix, either:
- return 401 from the store-server
- force user login on 403 error here: https://github.com/Rise-Vision/store/blob/master/web/script/app.js#L130
- verify and force user login before retrieving order here: https://github.com/Rise-Vision/store/blob/master/web/script/app.js#L578.

Thanks.

**Comment by stevesherrie** [comment]
@robb-price @alex-deaconu This should be taken care of in store-server. If you want to create a bug for me, I'll get to it @robb-price.

**Comment by brianloosbrock** [comment]
@robb-price @alex-deaconu @stevesherrie Robb lets create a bug in Store, add it Trello, and lets close this one. This should come after 932. Thanks

**Comment by robb-price** [comment]
@brianloosbrock @stevesherrie @alex-deaconu Created a bug in Store Server, a Trello Card, and I'm closing this bug.
