### ISSUE TITLE
When searching for a Company with a partial query, Company names that match the query should show at the top 

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/common-header#389]
<b>How it works now:</b>
From the Rise Vision Company, do a search for RVA Notice that it returns a LOT of stuff, and RVA Testing is not among the first Companies in the list.

For further clarification: http://www.screencast.com/t/qFmTWL5K6Wjs

<b>How it should work:</b>
Any companies that contain the exact partial query searched for should be at the top of the list.

**Comment by brianloosbrock** [comment]
@robb-price Is this still an issue?

**Comment by robb-price** [comment]
@brianloosbrock This is indeed still an issue.

**Comment by ByronDarlison** [comment]
@brianloosbrock @robb-price @alex-deaconu @ezequielc can you confirm the status of this issue? Is this still open? Thanks

**Comment by ezequielc** [comment]
@ByronDarlison @robb-price @alex-deaconu @brianloosbrock It looks like this is fixed. If I search for RVA, I get this RVA Testing as the first result:

![screenshot from 2016-02-02 16 37 57](https://cloud.githubusercontent.com/assets/7738553/12760019/5ea89e42-c9cb-11e5-9c88-3cfc57ce8bcd.png)

**Comment by ByronDarlison** [comment]
@ezequielc thanks! Closing
