### ISSUE TITLE
Gulp task that runs E2E tests on uglified version of CH

### ISSUE THREAD

**Issue by settinghead** [Rise-Vision/common-header#415]
Given a recent issue https://github.com/Rise-Vision/common-header/issues/412, a need to run tests on the code that goes to production becomes apparent.

**Comment by ByronDarlison** [comment]
@alex-deaconu @ezequielc is there any reason why this should be left open? Thanks!

**Comment by ezequielc** [comment]
@ByronDarlison I would close it. @alex-deaconu  Thoughts? Thanks

**Comment by alex-deaconu** [comment]
@ByronDarlison @ezequielc I'm good with closing. Thanks.
