### ISSUE TITLE
When cid is present in the URL parameter, userState returns user's company briefly before returning cid

### ISSUE THREAD

**Issue by settinghead** [Rise-Vision/common-header#417]
What should happen:

 When cid is present, ```selectedCompanyId()``` should only return ```cid```.

Reported by @alex-deaconu

**Comment by robb-price** [comment]
@ByronDarlison @brianloosbrock @stevesherrie @olegrise @tejohnso @alex-deaconu Closing this issue as we are tracking the upgrade of CH on <a href="https://trello.com/c/1RI7RlHd/234-upgrade-store-to-common-header-v1-0-3">this Trello card</a> for Store, and <a href="https://trello.com/c/2iEEqCl5/261-ui-related-fixes">this Trello card</a> for Storage.
