### ISSUE TITLE
A more robust solution to persist cid in route

### ISSUE THREAD

**Issue by settinghead** [Rise-Vision/common-header#418]
Perhaps via ```onRouteChange```. Needs investigation.

Related to https://github.com/Rise-Vision/store/issues/892

**Comment by brianloosbrock** [comment]
@robb-price Can you confirm this is fixed as part of deployment https://trello.com/c/6Y1cDpon/117-store-update-ch-version-to-include-country-code-fixes. Thanks.

**Comment by robb-price** [comment]
Verified and Closed.
