### ISSUE TITLE
Do not show spinner after user refocuses on page

### ISSUE THREAD

**Issue by settinghead** [Rise-Vision/common-header#431]
<b>How it works now:</b>
Log in as a Rise Vision user in Tab A. Open a new tab, and return Tab A. You will observe a few second's spinner that results from authentication checking.

<b>How it should work:</b>
No authentication spinner after a user refocuses to page.

**Comment by alex-deaconu** [comment]
@ByronDarlison apparently there's already an issue logged for this. Will pursue. Thanks.

**Comment by brianloosbrock** [comment]
No longer an issue. Closing.
