### ISSUE TITLE
When you mark a user as inactive and create a new user with the same name in the same Company, when you click on the user, it brings up the old inactive user instead of the new active one

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/common-header#434]
<b>How it works now:</b>
1. Mark a user as inactive in your Company.
2. Create a new user with the same username and email. 
3. Click on the newly created user in the Company Users list, notice that it brings up the old INACTIVE user, instead of the new one.

For further clarification: https://dl.dropboxusercontent.com/u/8237394/Screencasts/2014-12-19_1543.swf

**Comment by ByronDarlison** [comment]
@alex-deaconu @ezequielc @robb-price can you confirm the status of this issue? Is this still open? I think it is but I am not sure...

**Comment by ezequielc** [comment]
@ByronDarlison  @alex-deaconu @robb-price I just replicated it, issue is still open. Cheers

**Comment by ByronDarlison** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;N5wCG7gz&#x2F;1132-https-github-com-rise-vision-common-header-issues-434"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> https:&#x2F;&#x2F;github.com&#x2F;Rise-Vision&#x2F;common-header&#x2F;issues&#x2F;434</a>

**Comment by ByronDarlison** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;N5wCG7gz&#x2F;1132-https-github-com-rise-vision-common-header-issues-434"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> https:&#x2F;&#x2F;github.com&#x2F;Rise-Vision&#x2F;common-header&#x2F;issues&#x2F;434</a>

**Comment by ByronDarlison** [comment]
@ezequielc okay. Thanks. I have added to our backlog. Thanks

**Comment by ezequielc** [comment]
@robb-price This issue is fixed. Could you please confirm it is working? Thanks!
