### ISSUE TITLE
When switching companies, the isTest flag is not available

### ISSUE THREAD

**Issue by alex-deaconu** [Rise-Vision/common-header#437]
When switching companies, the company object retrieved via the list API is set as the selectedCompany object. This object does not contain all the company API fields, and since isTest is not one of them, the Test company banner does not show. To fix this, there are 2 possible solutions:
1. Add the fields to the list API
2. Retrieve the company object via CURD so all fields are present.

@alexey-rise what are your thoughts on the above? Is implementing the first option a good idea?

Thanks.

**Comment by alexey-rise** [comment]
@alex-deaconu I will add isTest to the company.list endpoint later today and let you know when it's done.

**Comment by robb-price** [comment]
Verified that this is corrected at https://store.risevision.com/~rvi/store-pr/pr-936/#/

**Comment by robb-price** [comment]
Verified and CLosed.
