### ISSUE TITLE
System Messages API call should not delay CH load

### ISSUE THREAD

**Issue by alex-deaconu** [Rise-Vision/common-header#449]
Discussed in https://github.com/Rise-Vision/core/issues/120.

As per @alanclayton: `There is a call for system messages that takes about 3 seconds and the UI is not presented until that is complete. I just get the overlay with spinner. [...] why do we wait for that to complete before showing the UI. Could that be done after the UI is loaded so the User isn't waiting?`

**Comment by ByronDarlison** [comment]
@alex-deaconu @alanclayton @brianloosbrock I believe this issue is now closed. Can you confirm?

**Comment by alanclayton** [comment]
@ByronDarlison Agreed.

**Comment by alex-deaconu** [comment]
@ByronDarlison @alanclayton System Messages are retrieved asynchronously. Closing. Thanks.

**Comment by ByronDarlison** [comment]
Thanks
