### ISSUE TITLE
Slow API response could cause two user/company API calls

### ISSUE THREAD

**Issue by alex-deaconu** [Rise-Vision/common-header#450]
As discussed in https://github.com/Rise-Vision/core/issues/120#issuecomment-72305928

http://www.screencast.com/t/2106fBNFwA

**Comment by ByronDarlison** [comment]
@alex-deaconu not sure the status of this. Could you confirm?

**Comment by alex-deaconu** [comment]
@ByronDarlison I believe you're correct. Fixed by https://github.com/Rise-Vision/common-header/pull/458. Closing. Thanks.
