### ISSUE TITLE
Confirm authentication when user regains focus on the page

### ISSUE THREAD

**Issue by alex-deaconu** [Rise-Vision/common-header#451]
Currently, authentication is confirmed only when the browser tab is switched. Improve this behaviour by verifying authentication when user regains focus on the page as well.

**Comment by ByronDarlison** [comment]
@alex-deaconu can you confirm what the status of this defect is and if it is open can you confirm what problem we need to solve here? Thanks

**Comment by alex-deaconu** [comment]
@ByronDarlison not fixed. To iterate, we currently have a mechanism that confirms the User's authentication when they switch tabs. This ensures they haven't logged out elsewhere, or switched accounts. However, it appears that mechanism doesn't always trigger, something that would need to be investigated. 

That is as of the creation of the issue, not sure what the situation is now. 

Thanks.

**Comment by ByronDarlison** [comment]
Okay. Opening a card for it. Thanks!

**Comment by ByronDarlison** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;hB0EES4G&#x2F;1138-https-github-com-rise-vision-common-header-issues-451"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> https:&#x2F;&#x2F;github.com&#x2F;Rise-Vision&#x2F;common-header&#x2F;issues&#x2F;451</a>

**Comment by alex-deaconu** [comment]
@ByronDarlison @ezequielc @olegrise I think we can close this issue. It is not a burning matter and so far the mechanism works "well enough". Thoughts? Thanks.

**Comment by ByronDarlison** [comment]
@alex-deaconu agreed.

**Comment by ezequielc** [comment]
@alex-deaconu agreed. Thanks
