### ISSUE TITLE
CH shows the email address, not the Username

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/common-header#468]
<b>How it works now:</b>
Log in with a user that has a different email address from their Username. Notice the email address shows in the CH instead of the Username:
![2015-02-26_0913](https://cloud.githubusercontent.com/assets/6862256/6393491/82bc525a-bd98-11e4-8ab3-f0e0eea06556.png)

<b>How it should work:</b>
It should show the Username instead of the email address.

**Comment by ByronDarlison** [comment]
@alex-deaconu @brianloosbrock @robb-price I believe this is now fixed. Can you confirm?

**Comment by alex-deaconu** [comment]
@ByronDarlison you're correct. Closing. Thanks.
