### ISSUE TITLE
Time Zone is saving, but not showing in CH

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/common-header#470]
<b>How it works now:</b>
Change the Time Zone in your Company Settings, notice that regardless of what you select, the dropdown stays as "Select Time Zone". Save and reopen the Company Settings, notice that it still says "Select Time Zone".

Go into the RVA, and the selection you saved is what is set for your Company.

For further clarification: https://dl.dropboxusercontent.com/u/8237394/Screencasts/2015-02-26_1009.swf

**Comment by alex-deaconu** [comment]
@robb-price I can't replicate this issue in the Displays App. Timezone is showing and editing correctly.

@stevesherrie does Store define its own TIMEZONES constant anywhere? 

Thanks.

**Comment by brianloosbrock** [comment]
@stevesherrie @alex-deaconu We can park this for now and come back to it. Thanks

**Comment by alex-deaconu** [comment]
@robb-price @brianloosbrock this issue should be fixed with the new CH version in the Store. Thanks!

**Comment by robb-price** [comment]
@alex-deaconu @brianloosbrock Looks like it is corrected.

Verified and Closed.
