### ISSUE TITLE
The entire CH header shows at the top of the In App Store

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/common-header#474]
<b>How it works now:</b>
Open the In App Store in the RVA, and notice that the entire CH header shows:
![2015-02-26_1241](https://cloud.githubusercontent.com/assets/6862256/6397758/17fc5b6e-bdb5-11e4-9c11-00786fd6eb98.png)

<b>How it should work:</b>
Only the Store, the Cart and the Close button should show.

**Comment by stevesherrie** [comment]
@robb-price @alex-deaconu Actually, this might have been a screwup with the rva I deployed. Give me one minute.

**Comment by stevesherrie** [comment]
@robb-price Fixed. Was just an issue with the RVA version I deployed for testing.
