### ISSUE TITLE
Remove 'Platform' from Store navigation. 

### ISSUE THREAD

**Issue by brianloosbrock** [Rise-Vision/common-header#475]
Now that we have the app navigation its redundant to have the Platform link in the main nav so lets remove it.

![image](https://cloud.githubusercontent.com/assets/6887543/6529003/74dd90dc-c3eb-11e4-8068-d1f943f576fb.png)

**Comment by alex-deaconu** [comment]
@brianloosbrock this issue should probably go to the Store repo. @olegrise FYI. Thanks.

**Comment by olegrise** [comment]
Yep, it's a Store issue.

**Comment by brianloosbrock** [comment]
@alex-deaconu Got it. Thanks.
