### ISSUE TITLE
Strip # from URL if there is no hash in state

### ISSUE THREAD

**Issue by alex-deaconu** [Rise-Vision/common-header#481]
When the re-direct from the authentication site returns, if there is no hash in state instead of setting the hash to blank, strip the hash altogether.

**Comment by ByronDarlison** [comment]
@alex-deaconu is this issue now closed?

**Comment by alex-deaconu** [comment]
@ByronDarlison we no longer use `#` characters in our URLs, so this should be a non-issue. Closing. Thanks.
