### ISSUE TITLE
Search results do not reflect search criteria

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/common-header#486]
1. Navigate to http://1-08-001.rvauser2.appspot.com/
2. Select the "Select Sub Company" from CH
3. In the search criteria enter `rise display`

Example, http://screencast.com/t/LvjhPJHEcR

Hundreds of companies are returned and neither of them contain the word `rise` or `display`

What should happen.
The results should only be those companies that contain the text provided in the search criteria

**Comment by alex-deaconu** [comment]
@alanclayton @mfisher11 I'm wondering if we could drop this one for the RVA CH release as well. Most companies don't have a lot of sub-companies so it's mostly a Rise Vision/Rise Display issue. Definitely need to fix, but I don't think the release should rely on it. Let me know what you think. Thanks.

**Comment by alanclayton** [comment]
@alex-deaconu I agree with you, but it is a huge pain for Support when trying to navigate to Companies for support reasons. Ray alone probably does this 50-100 times per day.

**Comment by alex-deaconu** [comment]
@alanclayton okay, got it. However, my worry is that this may be a Core issue. @alexey-rise any ideas on what could be happening here? Is the Core search too broad, or is the CH sending the query incorrectly?

A sample URL for this call is: 
`https://rvaserver2.appspot.com/_ah/api/core/v1/companies?companyId=f114ad26-949d-44b4-87e9-8528afc76ce4&count=20&search=rise%20display`

Thanks!

**Comment by olegrise** [comment]
@alex-deaconu I just tried `rise display` in the Store - all works as expected.

**Comment by alex-deaconu** [comment]
@olegrise hmm are you sure? It shows 100s of results for me: http://screencast.com/t/T6njWmkMUACD.

**Comment by olegrise** [comment]
@alex-deaconu  Hmm... :). When I run Store locally, it works correctly, but I might be using older version of CH.

**Comment by olegrise** [comment]
@alex-deaconu I'm have CH version v1.0.15. Strange.

**Comment by alex-deaconu** [comment]
@olegrise are you using rvacore-test or rvaserver2 locally?

**Comment by olegrise** [comment]
@alex-deaconu I was just going to say that I'm using rvacore-test. That's it.

**Comment by alexey-rise** [comment]
@alex-deaconu I am guessing there is either "rise" or "display" somewhere among the default values in the `settings` JSON field, so most companies are included. To avoid this I would suggest specifying explicit fields in the search string like RVA used to do (and how the Store does I believe): 

```
/d/company/b428b4e8-c8b9-41d5-8a10-b4193c789443/companies?auth=noauth&search=name:%20~\'rise%20display\'%20OR%20id:%20~\'rise%20display\'%20OR%20street:%20~\'rise%20display\'%20OR%20unit:%20~\'rise%20display\'%20OR%20city:%20~\'rise%20display\'%20OR%20province:%20~\'rise%20display\'%20OR%20country:%20~\'rise%20display\'%20OR%20postalCode:%20~\'rise%20display\'&sort=name&count=50&tqx=reqId%3A2
```

**Comment by olegrise** [comment]
`name: 'rise display'` worked for me.

**Comment by alex-deaconu** [comment]
@alexey-rise @olegrise nice. Will try that. Thanks for the suggestion!

**Comment by alex-deaconu** [comment]
@alanclayton @mfisher11 what fields do you guys think should be added to the search? So far I have:
"name", "id", "street", "unit", "city", "province", "country","postalCode", "telephone", "fax".

Thanks.

**Comment by alanclayton** [comment]
@alex-deaconu I don't think we need anything else. Thanks

**Comment by robb-price** [comment]
Verified at http://1-08-005.rvauser2.appspot.com/. Will close when verified in Production.

**Comment by robb-price** [comment]
Verified and Closed.
