### ISSUE TITLE
When you scroll through the Sub Company list, and then search, the results returned are doubled

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/common-header#492]
<b>How it works now:</b>
In the Rise Vision Test Co, click Select Sub Company and scroll down to the R's. Now do a search for "Robb's Testing". Notice that all Companies matching that criteria are returned twice in the list.

For further clarification: https://dl.dropboxusercontent.com/u/8237394/Screencasts/2015-03-25_1506.swf

**Comment by ByronDarlison** [comment]
@robb-price @alex-deaconu I believe this issue is now closed. Can you confirm?

**Comment by alex-deaconu** [comment]
@ByronDarlison @robb-price correct. This has been fixed. Closing. Thanks.
