### ISSUE TITLE
When you move a Company, the first line of the Address is missing for the Company you're moving and the Company you're moving it under

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/common-header#495]
<b>How it works now:</b>
Select Add Sub Company, and then Move a Company. Notice that when you enter the Auth Key of the Company you want to move and press Retrieve Company Details, Line 1 of the Address is missing from the results returned: 
![2015-03-27_1412](https://cloud.githubusercontent.com/assets/6862256/6874148/8f70a55a-d48b-11e4-8deb-30c01fb73e3e.png)

**Comment by ByronDarlison** [comment]
@robb-price @alex-deaconu is this still an issue?

**Comment by hcs0** [comment]
@ByronDarlison @robb-price @alex-deaconu The issue exists as described in the initial post.  However I don't see where one can access 'Line 1 Address' in Settings and Company Settings.

**Comment by ByronDarlison** [comment]
@hcs0 I think @robb-price means the street and unit are missing. @robb-price is this necessary? Is there any problem that this is causing that needs to be addressed or can this be closed?

**Comment by ByronDarlison** [comment]
@robb-price can you let us know re. this defect. We want to get this closed if possible.

**Comment by robb-price** [comment]
@ByronDarlison No one has brought it up, it was discovered during testing. It can be closed.

**Comment by ByronDarlison** [comment]
Thanks Robb
