### ISSUE TITLE
CH needs to dynamically load the State/Province list from the Core

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/common-header#513]
<b>How it works now:</b>
CH does not dynamically load the Core state/province list from here: https://rvacore-test.appspot.com/_ah/api/core/v1/countries, instead it is hardcoded.

It needs to be changed to dynamically load that list so we aren't maintaining it in two places if there are changes.

@alex-deaconu per our conversation about this, is there a reason that CH is using a hardcoded list instead of this list from the Core?

**Comment by alex-deaconu** [comment]
@robb-price nope, I wasn't aware that the provinces/states list was available in the countries API until today. 

Temporarily fixed Nunavut (NU) province code in CH Provinces list until this issue is addressed.

Thanks.

**Comment by olegrise** [comment]
@robb-price @alex-deaconu I don't think such API exists. At least I can''t find it.

**Comment by alex-deaconu** [comment]
@olegrise if you take a look at https://rvacore-test.appspot.com/_ah/api/core/v1/countries, the US and Canada entries include a sub-list of `states`. Thanks.

**Comment by olegrise** [comment]
@alex-deaconu I totally missed that. Thanks for pointing this out.

**Comment by ByronDarlison** [comment]
@robb-price @alex-deaconu @olegrise I believe this defect is now closed. Can you confirm?

**Comment by alex-deaconu** [comment]
@ByronDarlison nope this was never implemented. This feature still needs to be added to CH. Thanks.

**Comment by ByronDarlison** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;p1NsmIpL&#x2F;1141-https-github-com-rise-vision-common-header-issues-513"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> https:&#x2F;&#x2F;github.com&#x2F;Rise-Vision&#x2F;common-header&#x2F;issues&#x2F;513</a>

**Comment by ByronDarlison** [comment]
Okay. Added a card. Thanks
