### ISSUE TITLE
When logging into Store using CH 1.2.2, it just sits there on a blank page after you log in. Refreshing the page shows you the store.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/common-header#517]
<b>How it works now:</b>
Log into https://store-stage-1.risevision.com/ on Firefox, and notice that once you log in, it just sits on a blank page. If you refresh the page, it works as expected. This does not occur at the production version of the store (https://store.risevision.com)

The same thing does not happen in Chrome, or at http://1-08-008.rvauser2.appspot.com/

**Comment by ByronDarlison** [comment]
@robb-price @alex-deaconu I believe this issue is closed. Can you guys confirm. Thanks

**Comment by alex-deaconu** [comment]
@ByronDarlison @robb-price I'm not aware of this issue still occurring. It may be have been related to a specific, older CH version. @robb-price can you confirm? Thanks.

**Comment by ByronDarlison** [comment]
@alex-deaconu thanks. Closing. @robb-price if you think different let us know...

**Comment by robb-price** [comment]
@ByronDarlison @alex-deaconu Fine with me.
