### ISSUE TITLE
`selectedCompanyChanged` event not firing on `resetCompany` call

### ISSUE THREAD

**Issue by alex-deaconu** [Rise-Vision/common-header#531]
The `risevision.company.selectedCompanyChanged` event is not firing on `resetCompany()` call:
https://github.com/Rise-Vision/common-header/blob/master/src/js/svc-companystate.js#L96

Also unit test coverage is erroneous for this event:
https://github.com/Rise-Vision/common-header/blob/master/test/unit/svc-companystate-spec.js#L60
since the `broadcastSpy` is added here, first event trigger will always fulfil the `calledWith` dependency, so whether or not subsequent event calls trigger the spy is irrelevant.

**Comment by ByronDarlison** [comment]
@alex-deaconu I don't follow this defect. Can you confirm it's status?

**Comment by alex-deaconu** [comment]
@ByronDarlison this was fixed. Closing. Thanks.
