### ISSUE TITLE
When using ui-router and changing companies, using the back button doesn't update the selected company

### ISSUE THREAD

**Issue by alex-deaconu** [Rise-Vision/common-header#532]
Setting `$location.path()` parameters does not trigger the `$stateChangeSuccess` event when ui-router is used:
https://github.com/Rise-Vision/common-header/blob/master/src/js/dtv-common-header.js#L124

This results in the company not being switched when the back/forward buttons are used. Can be tested via the Store: switch company, press back, company should return to original company (doesn't), press forward, company should return to switched company (doesn't).

Solution:
http://stackoverflow.com/questions/16278951/angularjs-ui-router-equivalent-to-location-search

**Comment by ByronDarlison** [comment]
@alex-deaconu I just tested this and it looks like this is now closed. Do you concur?

**Comment by alex-deaconu** [comment]
@ByronDarlison we've had quite a few iterations over this functionality. Agreed, it should be fixed. Closing. Thanks.
