### ISSUE TITLE
Navigating to the Editor, Displays, or Schedules apps doesn't prompt you to sign in.

### ISSUE THREAD

**Issue by brianloosbrock** [Rise-Vision/common-header#533]
**How it works now**
If I go to Editor, Displays, or Schedules I don’t get told to do anything if I’m not signed in.

**How it should work**
It should prompt me to sign in if I'm not and then take me to the app.

![image](https://cloud.githubusercontent.com/assets/6887543/7595791/da7e7486-f8ae-11e4-88de-ac30bc14ddcd.png)

**Comment by brianloosbrock** [comment]
@alex-deaconu Hey Alex, I think we should resolve this in your next version of CH. Thoughts?

**Comment by ByronDarlison** [comment]
@brianloosbrock @alex-deaconu @rodrigopavezi I'm thinking we should take care of this as part of this card https://trello.com/c/nadQ0lY0 Alex, Rodrigo, do you concur? Thanks

**Comment by alex-deaconu** [comment]
@brianloosbrock @ByronDarlison this is more of an RVA change than CH. This is something we scoped out from the initial release of the RVA with CH, but we can definitely add it in after https://trello.com/c/nadQ0lY0 is completed. Thanks.

**Comment by ByronDarlison** [comment]
@alex-deaconu should we open this as a separate card and you take it after display app? Thanks

**Comment by alex-deaconu** [comment]
@ByronDarlison sure, added https://trello.com/c/dB0x19j8/295-rva-prompt-user-to-sign-in. To confirm, after the Displays App, and before the Data Tracking work, correct? Thanks.

**Comment by ByronDarlison** [comment]
@alex-deaconu thanks and yes, I think that sounds good...

**Comment by ByronDarlison** [comment]
@alex-deaconu I believe this is now closed. Can you confirm?

**Comment by alex-deaconu** [comment]
@ByronDarlison no this is not closed. When signed out, going to the RVA doesn't prompt you to sign in. However, as this only occurs with the RVA I think we can close this. Thanks.

**Comment by ByronDarlison** [comment]
@alex-deaconu agreed. Closing
