### ISSUE TITLE
App Launcher does not function on help.risevision.com.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/common-header#536]
Steps to reproduce:
1. Navigate to help.risevision.com
2. Select the app launcher

Result:
Clicking the app launcher has no effect.

How it should work:
The app launcher should open and load content.

OS:
OS X

Chrome Ver:
Version 42.0.2311.152 (64-bit)

**Comment by alex-deaconu** [comment]
@btfrise this is not a CH issue. The dependencies used on help.risevision.com (namely angular-bootstrap) are incorrect. A CH update for the app should resolve the issue. Thanks.

**Comment by btfrise** [comment]
@alex-deaconu should this be functioning now that you have released the new CH?

**Comment by ByronDarlison** [comment]
@rodrigopavezi can you please take a look at this first thing on Thursday. Thanks

**Comment by ByronDarlison** [comment]
The common header has been removed from help documentation. This is no longer relevant.
