### ISSUE TITLE
Saving user settings makes 4 API calls

### ISSUE THREAD

**Issue by alex-deaconu** [Rise-Vision/common-header#542]
Calling just one API method user.patch should be enough. Instead CH calls: `user.patch`, `user.get`, `user.get`, `company.get`.

**Comment by ByronDarlison** [comment]
@alex-deaconu is this issue still open? I think we fixed this didn't we?

**Comment by alex-deaconu** [comment]
@ByronDarlison yes, you're right. It was fixed. Closing. Thanks.
