### ISSUE TITLE
Delete key acts as 'Back' in some browsers

### ISSUE THREAD

**Issue by RV-Adrian** [Rise-Vision/common-header#580]
This seems to be an issue across most apps. Placing this in Common Header for now, just because it's unclear where it stems from. 
Video: https://goo.gl/l22hyH

Happens in Chrome and Opera on Mac, but not Safari.
Originally came up in: https://github.com/Rise-Vision/store/pull/1098

@alex-deaconu @rodrigopavezi @ezequielc @olegrise @ghislaineguerin FYI

**Comment by olegrise** [comment]
@alex-deaconu @rodrigopavezi @ezequielc here is another [video](https://drive.google.com/file/d/0Bzdv7xpveuRlOUFHLUZBUVdINVU/view?usp=sharing) that shows what happens when user hits backspace key after they open the modal to add content in Editor.

**Comment by ByronDarlison** [comment]
@RV-Adrian @olegrise good catch! Thanks
