### ISSUE TITLE
Misaligned common header in Store (mobile view)

### ISSUE THREAD

**Issue by RV-Adrian** [Rise-Vision/common-header#599]
Reference: http://goo.gl/qYLHWa

**Comment by ByronDarlison** [comment]
@RV-Adrian can you confirm if this is still open and if it is can you move this checklist item to it's own card and let's queue the work. Thanks

**Comment by ByronDarlison** [comment]
@RV-Adrian can you get back to us on this defect. We need to decide what to do with it. Thanks

**Comment by RV-Adrian** [comment]
@ByronDarlison Yes it's still open. Looks like the scope will have to be expanded beyond the Store as well, since it's an issue across the board. I'll queue up a card on the Apps board.

**Comment by RV-Adrian** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;yxt33OZB&#x2F;1142-issue-misaligned-common-header-599"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> [Issue] Misaligned common header  #599</a>

**Comment by ByronDarlison** [comment]
Thanks Adrian

**Comment by ByronDarlison** [comment]
@RV-Adrian is this issue still open?

**Comment by RV-Adrian** [comment]
Card is in Done, closing Issue now
