### ISSUE TITLE
Negative days on Plan trial

### ISSUE THREAD

**Issue by rudibravo** [Rise-Vision/common-header#783]
After the Plan Trial expires we expect the user to return to the free plan.
Instead the user is shown as having a negative remaining days of trial.

<img width="506" alt="screen shot 2018-03-13 at 1 14 48 pm" src="https://user-images.githubusercontent.com/160045/37355316-2ed25720-26c2-11e8-8989-78ea70879ba4.png">

**Comment by rudibravo** [comment]
@ezequielc @alex-deaconu @fjvallarino FYI

**Comment by fjvallarino** [comment]
@rudibravo interesting. The expectation is Core would return a different status when the Trial expires.

**Comment by fjvallarino** [comment]
This was deployed to master
